// <auto-generated />
using System;
using Jularr.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jularr.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928233839_Epoch4PostgresBaseline")]
    partial class Epoch4PostgresBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jularr.Web.Features.Acquisition.Api.AcquisitionApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("AcquisitionApiKeys");
                });

            modelBuilder.Entity("Jularr.Web.Features.Acquisition.History.AcquisitionHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AbsoluteEpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uuid");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("EventKind")
                        .HasColumnType("integer");

                    b.Property<string>("Indexer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QualityKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReleaseKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReleaseTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "SeasonNumber", "EpisodeNumber", "OccurredAtUtc");

                    b.ToTable("AcquisitionHistory");
                });

            modelBuilder.Entity("Jularr.Web.Features.Ai.AiSentenceExplanationCache", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ColloquialJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrammarJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CacheKey");

                    b.ToTable("AiSentenceExplanationCache");
                });

            modelBuilder.Entity("Jularr.Web.Features.Auth.OwnerAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("OwnerAccounts");
                });

            modelBuilder.Entity("Jularr.Web.Features.Books.BookEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EditionKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Isbn10")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Isbn13")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PublishedDate")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SourceExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Isbn10");

                    b.HasIndex("Isbn13");

                    b.HasIndex("WorkId", "EditionKey")
                        .IsUnique();

                    b.HasIndex("WorkId", "IsPrimary");

                    b.ToTable("BookEditions");
                });

            modelBuilder.Entity("Jularr.Web.Features.Books.BookFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("EditionId", "FileKey")
                        .IsUnique();

                    b.HasIndex("EditionId", "IsPrimary");

                    b.ToTable("BookFiles");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LearningStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PromptLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<long?>("QueuePosition")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("CourseId", "UnitId", "Mode")
                        .IsUnique();

                    b.HasIndex("ProfileId", "State", "NextReviewAt");

                    b.ToTable("LearningCards");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningCardReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "ReviewedAt");

                    b.HasIndex("ProfileId", "ClientEventId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "ReviewedAt");

                    b.ToTable("LearningCardReviews");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("PositionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("ProfileId", "SourceType", "SourceKey");

                    b.HasIndex("ProfileId", "UnitId", "SourceType", "SourceKey", "PositionKey")
                        .IsUnique();

                    b.ToTable("LearningContexts");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<bool>("ListeningEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("ProductionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("RecognitionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SentencePracticeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WritingEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SourceLanguage")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\"");

                    b.HasIndex("ProfileId", "SourceLanguage", "TargetLanguage")
                        .IsUnique();

                    b.ToTable("LearningCourses");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TermId")
                        .IsUnique();

                    b.ToTable("LearningUnits");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Reading")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageTag", "Text");

                    b.HasIndex("UnitId", "LanguageTag", "Text")
                        .IsUnique();

                    b.ToTable("LearningVariants");
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.LearningPreferences", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double>("DesiredRetention")
                        .HasColumnType("double precision");

                    b.Property<int>("NewWordsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewBatchSize")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId");

                    b.ToTable("LearningPreferences");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.Anime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.AnimeLocalMetadata", b =>
                {
                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("MyAnimeListId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Plot")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Premiered")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SourceFileLastWriteTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TmdbId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TvdbId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("AnimeId");

                    b.ToTable("AnimeLocalMetadata");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "SeasonNumber", "Number")
                        .IsUnique();

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.LibraryRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("ReconciliationIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("WakeBroadcastAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WakeMacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("WakeOnLanEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LibraryRoots");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAnalysis", b =>
                {
                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("integer");

                    b.Property<string>("Container")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("DynamicRange")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ProbeVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("SourceLastWriteTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VideoProfile")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("MediaFileId");

                    b.HasIndex("Status", "ProbeVersion");

                    b.ToTable("MediaAnalyses");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAnalysisStream", b =>
                {
                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChannelLayout")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Channels")
                        .HasColumnType("integer");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForced")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("MediaFileId", "StreamIndex");

                    b.ToTable("MediaAnalysisStreams");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("LibraryRootId", "EpisodeId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Jularr.Web.Features.MediaSegments.EpisodeMediaSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EndMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("MediaIdentity")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<long>("StartMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId", "Kind", "Source")
                        .IsUnique();

                    b.ToTable("EpisodeMediaSegments");
                });

            modelBuilder.Entity("Jularr.Web.Features.MediaSegments.EpisodeSegmentDetectionState", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SegmentsFound")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("EpisodeId");

                    b.ToTable("EpisodeSegmentDetectionStates");
                });

            modelBuilder.Entity("Jularr.Web.Features.Metadata.AnimeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageScore")
                        .HasColumnType("integer");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnglishTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodeDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Format")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NativeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreferredTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("RomajiTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Season")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("AnimeMetadata");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelAnimeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnimeExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AnimeProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ChapterEnd")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterStart")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EpisodeEnd")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeStart")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimeProvider", "AnimeExternalId");

                    b.HasIndex("WorkId", "ChapterStart", "ChapterEnd");

                    b.ToTable("NovelAnimeMappings");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnchorText")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CharacterOffset")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("ParagraphIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PositionPermille")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Style")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("SyncUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("WorkId");

                    b.HasIndex("ProfileId", "ChapterId");

                    b.HasIndex("ProfileId", "WorkId", "CreatedAt");

                    b.ToTable("NovelBookmarks");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.HasIndex("WorkId", "Number")
                        .IsUnique();

                    b.ToTable("NovelChapters");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ParagraphIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("WorkId");

                    b.HasIndex("ProfileId", "WorkId", "CreatedAt");

                    b.HasIndex("ProfileId", "ChapterId", "Language", "ParagraphIndex");

                    b.ToTable("NovelHighlights");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnchorLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("AnchorOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("AnchorParagraphIndex")
                        .HasColumnType("integer");

                    b.Property<string>("AnchorText")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("PositionPermille")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("WorkId");

                    b.HasIndex("ProfileId", "WorkId")
                        .IsUnique();

                    b.ToTable("NovelProgress");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "TargetLanguage", "ProviderId", "PromptVersion", "SourceHash")
                        .IsUnique();

                    b.ToTable("NovelTranslations");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelVolume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverAsset")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("SourceContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceStoragePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "Number")
                        .IsUnique();

                    b.HasIndex("WorkId", "SourceKey")
                        .IsUnique();

                    b.ToTable("NovelVolumes");
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MetadataChapterCount")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataDescription")
                        .HasColumnType("text");

                    b.Property<string>("MetadataExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetadataGenresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataNativeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetadataProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MetadataStatus")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MetadataTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MetadataVolumeCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MetadataProvider", "MetadataExternalId")
                        .IsUnique();

                    b.HasIndex("SourceProvider", "SourceKey")
                        .IsUnique();

                    b.ToTable("NovelWorks");
                });

            modelBuilder.Entity("Jularr.Web.Features.OfflineLibrary.NovelBookmarkTombstone", b =>
                {
                    b.Property<Guid>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("BookmarkId");

                    b.HasIndex("WorkId");

                    b.HasIndex("ProfileId", "WorkId");

                    b.ToTable("NovelBookmarkTombstones");
                });

            modelBuilder.Entity("Jularr.Web.Features.Progress.EpisodePlaybackHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PositionMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("ReachedEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("ProfileId", "LastPlayedAt");

                    b.ToTable("EpisodePlaybackHistory", (string)null);
                });

            modelBuilder.Entity("Jularr.Web.Features.Progress.EpisodeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<long>("PositionMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("ProfileId", "EpisodeId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "UpdatedAt");

                    b.ToTable("EpisodeProgress");
                });

            modelBuilder.Entity("Jularr.Web.Features.Progress.ProfilePlaybackPreferences", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("AutoplayNext")
                        .HasColumnType("boolean");

                    b.Property<double>("DefaultPlaybackSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<string>("PreferredAudioLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PreferredSubtitleLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfilePlaybackPreferences");
                });

            modelBuilder.Entity("Jularr.Web.Features.ReaderPreferences.ReaderPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AutoContinueChapters")
                        .HasColumnType("boolean");

                    b.Property<double?>("AutoScrollSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("BackgroundAssetId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double?>("BackgroundIntensity")
                        .HasColumnType("double precision");

                    b.Property<string>("BackgroundMotionMode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BookmarkColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BookmarkStyle")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ChapterStyle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FontFamily")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("FontSizeRem")
                        .HasColumnType("double precision");

                    b.Property<bool?>("FuriganaEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GenreArtworkEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GenreTheme")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<bool?>("Hyphenation")
                        .HasColumnType("boolean");

                    b.Property<double?>("LineHeight")
                        .HasColumnType("double precision");

                    b.Property<string>("PageTransition")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("PaperStyle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("ParagraphIndent")
                        .HasColumnType("boolean");

                    b.Property<double?>("ParagraphSpacingEm")
                        .HasColumnType("double precision");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReadingMode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool?>("ShowIllustrations")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ShowPageNumbers")
                        .HasColumnType("boolean");

                    b.Property<string>("TextAlignment")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int?>("TextWidthPx")
                        .HasColumnType("integer");

                    b.Property<double?>("ThemeBlurPx")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeBrightness")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeContrast")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeEffectStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeGrainStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeParallaxStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeSaturation")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeTextBackdropStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeTintStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeVignetteStrength")
                        .HasColumnType("double precision");

                    b.Property<bool?>("TtsAutoContinueChapters")
                        .HasColumnType("boolean");

                    b.Property<double?>("TtsPitch")
                        .HasColumnType("double precision");

                    b.Property<string>("TtsProviderId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<double?>("TtsRate")
                        .HasColumnType("double precision");

                    b.Property<string>("TtsVoiceIds")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<double?>("TtsVolume")
                        .HasColumnType("double precision");

                    b.Property<bool?>("TwoPageSpread")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.HasIndex("ProfileId", "ScopeKey")
                        .IsUnique();

                    b.ToTable("ReaderPreferences");
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleCue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EndMs")
                        .HasColumnType("integer");

                    b.Property<int>("StartMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubtitleTrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubtitleTrackId", "StartMs");

                    b.ToTable("SubtitleCues");
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleLanguageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CutoffPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SubtitleLanguageProfiles");
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleLanguageProfileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Forced")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Sdh")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SortOrder");

                    b.ToTable("SubtitleLanguageProfileItems");
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleProfileAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LibraryRootId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MediaType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRootId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("MediaType", "LibraryRootId");

                    b.ToTable("SubtitleProfileAssignments");
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Forced")
                        .HasColumnType("boolean");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("Sdh")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("EpisodeId", "Language");

                    b.ToTable("SubtitleTracks");
                });

            modelBuilder.Entity("Jularr.Web.Features.Vocabulary.EpisodeTerm", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<int>("FirstCueStartMs")
                        .HasColumnType("integer");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer");

                    b.HasKey("EpisodeId", "TermId");

                    b.HasIndex("TermId");

                    b.ToTable("EpisodeTerms");
                });

            modelBuilder.Entity("Jularr.Web.Features.Vocabulary.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Meaning")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reading")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Language", "Canonical")
                        .IsUnique();

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("Jularr.Web.Features.Acquisition.History.AcquisitionHistoryEntry", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Books.BookEdition", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Books.BookFile", b =>
                {
                    b.HasOne("Jularr.Web.Features.Books.BookEdition", null)
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningCard", b =>
                {
                    b.HasOne("Jularr.Web.Features.Learning.Courses.LearningCourse", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Learning.Courses.LearningUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningCardReview", b =>
                {
                    b.HasOne("Jularr.Web.Features.Learning.Courses.LearningCard", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningContext", b =>
                {
                    b.HasOne("Jularr.Web.Features.Learning.Courses.LearningUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningUnit", b =>
                {
                    b.HasOne("Jularr.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Jularr.Web.Features.Learning.Courses.LearningVariant", b =>
                {
                    b.HasOne("Jularr.Web.Features.Learning.Courses.LearningUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.AnimeLocalMetadata", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Anime", null)
                        .WithOne()
                        .HasForeignKey("Jularr.Web.Features.Library.AnimeLocalMetadata", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.Episode", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAnalysis", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.MediaFile", null)
                        .WithOne()
                        .HasForeignKey("Jularr.Web.Features.Library.MediaAnalysis", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAnalysisStream", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.MediaAnalysis", null)
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaFile", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Library.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.MediaSegments.EpisodeMediaSegment", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.MediaSegments.EpisodeSegmentDetectionState", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Metadata.AnimeMetadata", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Anime", null)
                        .WithOne()
                        .HasForeignKey("Jularr.Web.Features.Metadata.AnimeMetadata", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelAnimeMapping", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelBookmark", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelChapter", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelVolume", null)
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelHighlight", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelProgress", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelTranslation", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Novels.NovelVolume", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.OfflineLibrary.NovelBookmarkTombstone", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Progress.EpisodePlaybackHistoryEntry", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Progress.EpisodeProgress", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.ReaderPreferences.ReaderPreference", b =>
                {
                    b.HasOne("Jularr.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleCue", b =>
                {
                    b.HasOne("Jularr.Web.Features.Subtitles.SubtitleTrack", null)
                        .WithMany()
                        .HasForeignKey("SubtitleTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleLanguageProfileItem", b =>
                {
                    b.HasOne("Jularr.Web.Features.Subtitles.SubtitleLanguageProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleProfileAssignment", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jularr.Web.Features.Subtitles.SubtitleLanguageProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Subtitles.SubtitleTrack", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Vocabulary.EpisodeTerm", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jularr.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
