// <auto-generated />
using System;
using AniLingo.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniLingo.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    public partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AniLingo.Web.Features.Ai.AiSentenceExplanationCache", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColloquialJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrammarJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CacheKey");

                    b.ToTable("AiSentenceExplanationCache");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.LearningPreferences", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("DesiredRetention")
                        .HasColumnType("REAL");

                    b.Property<int>("ReviewBatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewWordsPerDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("LearningPreferences");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TermId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.HasIndex("ProfileId", "ReviewedAt");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.UserTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LearningStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long?>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TermId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.HasIndex("ProfileId", "TermId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "State", "NextReviewAt");

                    b.HasIndex("LearningStartedAt", "QueuePosition");

                    b.ToTable("UserTerms");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.Anime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "SeasonNumber", "Number")
                        .IsUnique();

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.LibraryRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LibraryRoots");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("LibraryRootId", "EpisodeId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Metadata.AnimeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RomajiTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("AnimeMetadata");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleCue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubtitleTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubtitleTrackId", "StartMs");

                    b.ToTable("SubtitleCues");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("EpisodeId", "Language");

                    b.ToTable("SubtitleTracks");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Vocabulary.EpisodeTerm", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TermId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstCueStartMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Occurrences")
                        .HasColumnType("INTEGER");

                    b.HasKey("EpisodeId", "TermId");

                    b.HasIndex("TermId");

                    b.ToTable("EpisodeTerms");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Vocabulary.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reading")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Language", "Canonical")
                        .IsUnique();

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Review", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.UserTerm", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.Episode", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaFile", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Library.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Metadata.AnimeMetadata", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Anime", null)
                        .WithOne()
                        .HasForeignKey("AniLingo.Web.Features.Metadata.AnimeMetadata", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleCue", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Subtitles.SubtitleTrack", null)
                        .WithMany()
                        .HasForeignKey("SubtitleTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleTrack", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Vocabulary.EpisodeTerm", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
