// <auto-generated />
using System;
using AniLingo.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniLingo.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    public partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AniLingo.Web.Features.Auth.OwnerAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("OwnerAccounts");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Ai.AiSentenceExplanationCache", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColloquialJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrammarJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CacheKey");

                    b.ToTable("AiSentenceExplanationCache");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.LearningPreferences", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("DesiredRetention")
                        .HasColumnType("REAL");

                    b.Property<int>("ReviewBatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewWordsPerDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("LearningPreferences");
                });

            modelBuilder.Entity("AniLingo.Web.Features.ReaderPreferences.ReaderPreference", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<double?>("AutoScrollSpeed").HasColumnType("REAL");
                    b.Property<double?>("BackgroundIntensity").HasColumnType("REAL");
                    b.Property<string>("BackgroundAssetId").HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<string>("BackgroundMotionMode").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<double?>("ThemeEffectStrength").HasColumnType("REAL");
                    b.Property<double?>("ThemeBrightness").HasColumnType("REAL");
                    b.Property<double?>("ThemeContrast").HasColumnType("REAL");
                    b.Property<double?>("ThemeSaturation").HasColumnType("REAL");
                    b.Property<double?>("ThemeBlurPx").HasColumnType("REAL");
                    b.Property<double?>("ThemeVignetteStrength").HasColumnType("REAL");
                    b.Property<double?>("ThemeGrainStrength").HasColumnType("REAL");
                    b.Property<double?>("ThemeTextBackdropStrength").HasColumnType("REAL");
                    b.Property<double?>("ThemeParallaxStrength").HasColumnType("REAL");
                    b.Property<double?>("ThemeTintStrength").HasColumnType("REAL");
                    b.Property<string>("BookmarkColor").HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<string>("BookmarkStyle").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<string>("ChapterStyle").HasMaxLength(32).HasColumnType("TEXT");
                    b.Property<string>("FontFamily").HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<double?>("FontSizeRem").HasColumnType("REAL");
                    b.Property<bool?>("GenreArtworkEnabled").HasColumnType("INTEGER");
                    b.Property<string>("GenreTheme").HasMaxLength(48).HasColumnType("TEXT");
                    b.Property<double?>("LineHeight").HasColumnType("REAL");
                    b.Property<string>("PageTransition").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<string>("PaperStyle").HasMaxLength(32).HasColumnType("TEXT");
                    b.Property<double?>("ParagraphSpacingEm").HasColumnType("REAL");
                    b.Property<string>("ProfileId").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("ReadingMode").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<string>("ScopeKey").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("TextAlignment").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<int?>("TextWidthPx").HasColumnType("INTEGER");
                    b.Property<bool?>("TtsAutoContinueChapters").HasColumnType("INTEGER");
                    b.Property<double?>("TtsPitch").HasColumnType("REAL");
                    b.Property<string>("TtsProviderId").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<double?>("TtsRate").HasColumnType("REAL");
                    b.Property<string>("TtsVoiceIds").HasMaxLength(8000).HasColumnType("TEXT");
                    b.Property<double?>("TtsVolume").HasColumnType("REAL");
                    b.Property<bool?>("TwoPageSpread").HasColumnType("INTEGER");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid?>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("WorkId");
                    b.HasIndex("ProfileId", "ScopeKey").IsUnique();
                    b.ToTable("ReaderPreferences");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LearningStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long?>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("CourseId", "UnitId", "Mode")
                        .IsUnique();

                    b.HasIndex("ProfileId", "State", "NextReviewAt");

                    b.ToTable("LearningCards");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningCardReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "ReviewedAt");

                    b.HasIndex("ProfileId", "ClientEventId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "ReviewedAt");

                    b.ToTable("LearningCardReviews");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("SourceType", "SourceKey");

                    b.ToTable("LearningContexts");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ListeningEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProductionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecognitionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SentencePracticeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WritingEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SourceLanguage")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = 1");

                    b.HasIndex("ProfileId", "SourceLanguage", "TargetLanguage")
                        .IsUnique();

                    b.ToTable("LearningCourses");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TermId")
                        .IsUnique();

                    b.ToTable("LearningUnits");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reading")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageTag", "Text");

                    b.HasIndex("UnitId", "LanguageTag", "Text")
                        .IsUnique();

                    b.ToTable("LearningVariants");
                });


            modelBuilder.Entity("AniLingo.Web.Features.Progress.EpisodeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("ProfileId", "EpisodeId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "UpdatedAt");

                    b.ToTable("EpisodeProgress");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Progress.EpisodePlaybackHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReachedEnd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("ProfileId", "LastPlayedAt");

                    b.ToTable("EpisodePlaybackHistory");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Progress.ProfilePlaybackPreferences", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoplayNext")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultPlaybackSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<string>("PreferredAudioLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredSubtitleLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfilePlaybackPreferences");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.Anime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "SeasonNumber", "Number")
                        .IsUnique();

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.LibraryRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReconciliationIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WakeBroadcastAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WakeMacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WakeOnLanEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LibraryRoots");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaAnalysis", b =>
                {
                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Container")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("DynamicRange")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProbeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SourceLastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoProfile")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFileId");

                    b.HasIndex("Status", "ProbeVersion");

                    b.ToTable("MediaAnalyses");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaAnalysisStream", b =>
                {
                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelLayout")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("MediaFileId", "StreamIndex");

                    b.ToTable("MediaAnalysisStreams");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("LibraryRootId", "EpisodeId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("AniLingo.Web.Features.MediaSegments.EpisodeMediaSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaIdentity")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId", "Kind", "Source")
                        .IsUnique();

                    b.ToTable("EpisodeMediaSegments");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Metadata.AnimeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RomajiTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("AnimeMetadata");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleCue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubtitleTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubtitleTrackId", "StartMs");

                    b.ToTable("SubtitleCues");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("EpisodeId", "Language");

                    b.ToTable("SubtitleTracks");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Vocabulary.EpisodeTerm", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TermId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstCueStartMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Occurrences")
                        .HasColumnType("INTEGER");

                    b.HasKey("EpisodeId", "TermId");

                    b.HasIndex("TermId");

                    b.ToTable("EpisodeTerms");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Vocabulary.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reading")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Language", "Canonical")
                        .IsUnique();

                    b.ToTable("Terms");
                });


            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelAnimeMapping", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("AnimeExternalId").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("AnimeProvider").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<int>("ChapterEnd").HasColumnType("INTEGER");
                    b.Property<int>("ChapterStart").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("EpisodeEnd").HasColumnType("INTEGER");
                    b.Property<int>("EpisodeStart").HasColumnType("INTEGER");
                    b.Property<string>("Label").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<int>("SeasonNumber").HasColumnType("INTEGER");
                    b.Property<string>("Source").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("AnimeProvider", "AnimeExternalId");
                    b.HasIndex("WorkId", "ChapterStart", "ChapterEnd");
                    b.ToTable("NovelAnimeMappings");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelChapter", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("ContentJson").HasColumnType("TEXT");
                    b.Property<DateTime>("ImportedAt").HasColumnType("TEXT");
                    b.Property<int>("Number").HasColumnType("INTEGER");
                    b.Property<string>("OriginalText").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("PublishedAt").HasColumnType("TEXT");
                    b.Property<string>("SourceHash").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                    b.Property<string>("SourceUrl").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid>("VolumeId").HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("VolumeId");
                    b.HasIndex("WorkId", "Number").IsUnique();
                    b.ToTable("NovelChapters");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelVolume", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("CoverAsset").HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<DateTime>("ImportedAt").HasColumnType("TEXT");
                    b.Property<string>("Kind").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<int>("Number").HasColumnType("INTEGER");
                    b.Property<string>("SourceContentHash").HasMaxLength(64).HasColumnType("TEXT");
                    b.Property<string>("SourceFileName").HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<string>("SourceKey").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Title").HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("WorkId", "Number").IsUnique();
                    b.HasIndex("WorkId", "SourceKey").IsUnique();
                    b.ToTable("NovelVolumes");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelBookmark", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("AnchorText").HasMaxLength(180).HasColumnType("TEXT");
                    b.Property<int>("CharacterOffset").HasColumnType("INTEGER");
                    b.Property<Guid>("ChapterId").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Label").HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<string>("Style").HasMaxLength(24).HasColumnType("TEXT");
                    b.Property<string>("Color").HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<string>("Language").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<int?>("ParagraphIndex").HasColumnType("INTEGER");
                    b.Property<int>("PositionPermille").HasColumnType("INTEGER");
                    b.Property<string>("ProfileId").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ChapterId");
                    b.HasIndex("ProfileId", "ChapterId");
                    b.HasIndex("ProfileId", "WorkId", "CreatedAt");
                    b.HasIndex("WorkId");
                    b.ToTable("NovelBookmarks");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelHighlight", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<Guid>("ChapterId").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("EndOffset").HasColumnType("INTEGER");
                    b.Property<string>("Language").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<string>("Note").HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<int>("ParagraphIndex").HasColumnType("INTEGER");
                    b.Property<string>("ProfileId").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<int>("StartOffset").HasColumnType("INTEGER");
                    b.Property<string>("Text").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ChapterId");
                    b.HasIndex("ProfileId", "ChapterId", "Language", "ParagraphIndex");
                    b.HasIndex("ProfileId", "WorkId", "CreatedAt");
                    b.HasIndex("WorkId");
                    b.ToTable("NovelHighlights");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelProgress", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("AnchorLanguage").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<int>("AnchorOffset").HasColumnType("INTEGER");
                    b.Property<int?>("AnchorParagraphIndex").HasColumnType("INTEGER");
                    b.Property<string>("AnchorText").HasMaxLength(180).HasColumnType("TEXT");
                    b.Property<Guid>("ChapterId").HasColumnType("TEXT");
                    b.Property<int>("PositionPermille").HasColumnType("INTEGER");
                    b.Property<string>("ProfileId").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ChapterId");
                    b.HasIndex("ProfileId", "WorkId").IsUnique();
                    b.HasIndex("WorkId");
                    b.ToTable("NovelProgress");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelTranslation", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<Guid>("ChapterId").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("PromptVersion").HasColumnType("INTEGER");
                    b.Property<string>("ProviderId").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("SourceHash").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                    b.Property<string>("TargetLanguage").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<string>("Text").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ChapterId", "TargetLanguage", "ProviderId", "PromptVersion", "SourceHash").IsUnique();
                    b.ToTable("NovelTranslations");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Books.BookEdition", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Author").HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("EditionKey").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<bool>("IsPrimary").HasColumnType("INTEGER");
                    b.Property<string>("Isbn10").HasMaxLength(10).HasColumnType("TEXT");
                    b.Property<string>("Isbn13").HasMaxLength(13).HasColumnType("TEXT");
                    b.Property<string>("Language").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                    b.Property<string>("PublishedDate").HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("Publisher").HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<string>("SourceExternalId").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("SourceProvider").HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("Title").HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid>("WorkId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Isbn10");
                    b.HasIndex("Isbn13");
                    b.HasIndex("WorkId", "EditionKey").IsUnique();
                    b.HasIndex("WorkId", "IsPrimary");
                    b.ToTable("BookEditions");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Books.BookFile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                    b.Property<Guid>("EditionId").HasColumnType("TEXT");
                    b.Property<string>("FileKey").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<string>("FileName").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<string>("Format").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
                    b.Property<DateTime>("ImportedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsPrimary").HasColumnType("INTEGER");
                    b.Property<string>("MediaType").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<long>("SizeBytes").HasColumnType("INTEGER");
                    b.Property<string>("SourceKind").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("SourceUrl").HasMaxLength(2048).HasColumnType("TEXT");
                    b.Property<string>("StoragePath").HasMaxLength(2048).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ContentHash");
                    b.HasIndex("EditionId", "FileKey").IsUnique();
                    b.HasIndex("EditionId", "IsPrimary");
                    b.ToTable("BookFiles");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelWork", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Author").HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<string>("BannerImageUrl").HasMaxLength(2048).HasColumnType("TEXT");
                    b.Property<string>("CoverImageUrl").HasMaxLength(2048).HasColumnType("TEXT");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<string>("Format").HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<DateTime>("ImportedAt").HasColumnType("TEXT");
                    b.Property<int?>("MetadataChapterCount").HasColumnType("INTEGER");
                    b.Property<string>("MetadataDescription").HasColumnType("TEXT");
                    b.Property<string>("MetadataExternalId").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("MetadataGenresJson").HasColumnType("TEXT");
                    b.Property<string>("MetadataNativeTitle").HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<string>("MetadataProvider").HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("MetadataStatus").HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("MetadataTitle").HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<int?>("MetadataVolumeCount").HasColumnType("INTEGER");
                    b.Property<string>("SourceKey").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("SourceProvider").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("SourceUrl").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("MetadataProvider", "MetadataExternalId").IsUnique();
                    b.HasIndex("SourceProvider", "SourceKey").IsUnique();
                    b.ToTable("NovelWorks");
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningCard", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Learning.Courses.LearningCourse", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Learning.Courses.LearningUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningCardReview", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Learning.Courses.LearningCard", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningContext", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Learning.Courses.LearningUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningUnit", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AniLingo.Web.Features.Learning.Courses.LearningVariant", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Learning.Courses.LearningUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Progress.EpisodeProgress", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Progress.EpisodePlaybackHistoryEntry", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.Episode", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaAnalysis", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.MediaFile", null)
                        .WithOne()
                        .HasForeignKey("AniLingo.Web.Features.Library.MediaAnalysis", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaAnalysisStream", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.MediaAnalysis", null)
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Library.MediaFile", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Library.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.MediaSegments.EpisodeMediaSegment", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Metadata.AnimeMetadata", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Anime", null)
                        .WithOne()
                        .HasForeignKey("AniLingo.Web.Features.Metadata.AnimeMetadata", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleCue", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Subtitles.SubtitleTrack", null)
                        .WithMany()
                        .HasForeignKey("SubtitleTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Subtitles.SubtitleTrack", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Vocabulary.EpisodeTerm", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Vocabulary.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.ReaderPreferences.ReaderPreference", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelAnimeMapping", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Books.BookEdition", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Books.BookFile", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Books.BookEdition", null)
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelChapter", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelVolume", null)
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelVolume", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelBookmark", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelHighlight", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelProgress", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniLingo.Web.Features.Novels.NovelWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniLingo.Web.Features.Novels.NovelTranslation", b =>
                {
                    b.HasOne("AniLingo.Web.Features.Novels.NovelChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

#pragma warning restore 612, 618
        }
    }
}
