using AniLingo.Web.Features.Subtitles;

namespace AniLingo.Tests;

[TestClass]
public sealed class SubtitleParserTests
{
    [TestMethod]
    public void ParsesSrtAndNormalizesFormatting()
    {
        const string content = """
            1
            00:00:01,250 --> 00:00:03,500
            <i>何してるの？</i>

            2
            00:00:04,000 --> 00:00:05,200
            まだ諦めてない。
            """;

        var cues = SubtitleParser.ParseSrt(content);

        Assert.AreEqual(2, cues.Count);
        Assert.AreEqual(1250, cues[0].StartMs);
        Assert.AreEqual("何してるの？", cues[0].Text);
    }

    [TestMethod]
    public void ParsesAssDialogueUsingDeclaredFormat()
    {
        const string content = """
            [Script Info]
            Title: Example

            [Events]
            Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
            Dialogue: 0,0:00:01.20,0:00:03.40,Default,,0,0,0,,{\i1}学校に行く{\i0}\N今から
            """;

        var cues = SubtitleParser.ParseAss(content);

        Assert.AreEqual(1, cues.Count);
        Assert.AreEqual(1200, cues[0].StartMs);
        Assert.AreEqual("学校に行く 今から", cues[0].Text);
    }

    [TestMethod]
    public void ParsesSsaV4DialogueThroughFormatDispatch()
    {
        const string content = """
            [Script Info]
            ScriptType: v4.00

            [Events]
            Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
            Dialogue: Marked=0,0:01:02.50,0:01:04.00,Default,,0000,0000,0000,,猫が走る
            """;

        var cues = SubtitleParser.ParseFormat("ssa", content);

        Assert.AreEqual(1, cues.Count);
        Assert.AreEqual(62500, cues[0].StartMs);
        Assert.AreEqual(64000, cues[0].EndMs);
        Assert.AreEqual("猫が走る", cues[0].Text);
    }

    [TestMethod]
    public void ParsesVttCuesSkippingMetadataBlocksAndRubyText()
    {
        const string content = """
            WEBVTT - Japanese

            NOTE Generated by a test

            STYLE
            ::cue { color: white; }

            intro
            00:01.250 --> 00:03.500 align:start position:10%
            <v 先生><ruby>学校<rt>がっこう</rt></ruby>に行く</v>
            &lt;今から&gt;

            01:00:04.000 --> 01:00:05.200
            <c.yellow>まだ</c>諦めてない&amp;
            """;

        var cues = SubtitleParser.ParseFormat(".vtt", content);

        Assert.AreEqual(2, cues.Count);
        Assert.AreEqual(1250, cues[0].StartMs);
        Assert.AreEqual(3500, cues[0].EndMs);
        Assert.AreEqual("学校に行く <今から>", cues[0].Text);
        Assert.AreEqual(3604000, cues[1].StartMs);
        Assert.AreEqual(3605200, cues[1].EndMs);
        Assert.AreEqual("まだ諦めてない&", cues[1].Text);
    }
}
